print("\n")
print("\n")
print("        ***                  ***        ")
print("       *****                *****       ")
print("        ***                  ***        ")
print("                                        ")
print("   *                                *   ")
print("   ***                            ***   ")
print("    ****                        ****    ")
print("      ****************************      ")
print("         **********************         ")
print("            ****************            ")
print("\n")
print("\n")